-- MySQL Script generated by MySQL Workbench
-- 03/27/22 12:34:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`balance` (
  `id` INT NOT NULL,
  `balance` DECIMAL NOT NULL,
  `save` VARCHAR(45) NOT NULL,
  `time` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `balance_id` INT NOT NULL,
  PRIMARY KEY (`id`, `balance_id`),
  INDEX `fk_user_balance1_idx` (`balance_id` ASC),
  CONSTRAINT `fk_user_balance1`
    FOREIGN KEY (`balance_id`)
    REFERENCES `mydb`.`balance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`target` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_target_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_target_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`income` (
  `id` INT NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `balance_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_income_balance1_idx` (`balance_id` ASC),
  CONSTRAINT `fk_income_balance1`
    FOREIGN KEY (`balance_id`)
    REFERENCES `mydb`.`balance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expenses` (
  `id` INT NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `balance_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_expenses_balance1_idx` (`balance_id` ASC),
  CONSTRAINT `fk_expenses_balance1`
    FOREIGN KEY (`balance_id`)
    REFERENCES `mydb`.`balance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
